services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:v3.5.0 
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_FILE=${LOG_FILE:-none}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=America/New_York
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped
    logging: { options: { max-size: '50',  max-file: '5' } }
